name: auto-generate-docsify-sidebar
on:
  push:
    branches:
      - master

jobs:
  master-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: generate _sidebar.md
        run: |
          bash ./docs/sidebar.sh

      - name: push _sidebar.md to branch gh-pages
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REF: github.com/${{github.repository}}
          MYEMAIL: givedrug@outlook.com
          MYNAME: ${{github.repository_owner}}
        run: |
          cd docs
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}"
          git init
          git remote add origin https://${REF}
          git add . 
          git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
          git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

      - name: checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: add first title
        run: |
          bash ./addFirstTitle.sh
